### ISSUE TITLE
Cython reported as active: false under MSYS2?

### ISSUE THREAD

**Issue by sdbbs** [kevinpt/ripyl#4]
Hi,

Thanks for this great software! I finally managed to install it for Python3 under MSYS2 on Windows 10; I also tried to install and enable the Cython support.

When I try to run the demo, everything seems to work, and I get a Matplotlib figure - this is the console transcript:

```
$ RIPYL_CYTHON=1 ripyl_demo -p uart
Cython status
  Enabled: True
  Prebuild: True
  Active: False
  Patched objects:

** Ripyl demo **


UART protocol


Protocol parameters:
  Messages:
   72
   101
   108
   108
   111
   44
   32
   119
   111
   114
   108
   100
   33
  baud: 115200
  decode baud: None
  bits: 8
  parity: even
  stop bits: 1
  polarity: 1
Waveform parameters:
  sample rate: 11.520 MHz
  rise time: 607.6 ns
  SNR: 40.0 dB

Decoded messages:
  72
  101
  108
  108
  111
  44
  32
  119
  111
  114
  108
  100
  33
  (matches input message)
```

What surprises me here, is that even if I've used the environment variable `RIPYL_CYTHON=1` explicitly, the console log still reports `Active: False` for `Cython status`.

So I'm not sure if this message really tells me Cython is not active (even if it is enabled, and prebuilt?), or is some other aspect of it not active? How would I check?

**Comment by kurianpolachan-iiitb** [comment]
@sdbbs Can you explain how you managed to install ripyl in Python3. When I installed and try to import ripyl in Python3, I get the following error. 

import ripyl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/IIIT-B/Documents/VLC-LE-Dataset-Processing/ripyl-master/ripyl/__init__.py", line 13, in <module>
    import ripyl.config
  File "/Users/IIIT-B/Documents/VLC-LE-Dataset-Processing/ripyl-master/ripyl/config.py", line 101
    print 'Cython status'
    ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
