### ISSUE TITLE
Cannot install with the latest version of setuptools

### ISSUE THREAD

**Issue by LastStarDust** [kevinpt/ripyl#7]
Hello.
I am trying to install it in Windows using Python 3.8.
The setup fails if I use the latest version of setuptools v58.0.4 but succeeds if I use v45.3.0

The error I get is:
```
python.exe .\setup.py install
Traceback (most recent call last):
  File ".\setup.py", line 4, in <module>
    from setuptools import setup, Extension, Feature
ImportError: cannot import name 'Feature' from 'setuptools' (.venv\lib\site-packages\setuptools\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\setup.py", line 6, in <module>
    sys.exit('ERROR: setuptools is required.\nTry using "pip install setuptools".')
NameError: name 'sys' is not defined

```

**Comment by LastStarDust** [comment]
I close this because the repository is obviously abandoned.
